baseURL = 'https://blog.jaxwang.top/'
languageCode = 'en-us'
title = 'Jackson Blog'
theme = 'xmin-jax'
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_cache$" ]
footnotereturnlinkcontents = "â†©"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 2
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 3
  [[menus.main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 4
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 5
  [[menus.main]]
    name = 'RSS'
    pageRef = '/rss'
    weight = 6

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/p/:slug/"

[params]
description = "A website built through Hugo and blogdown."
footer = "&copy; [Jackson Wang](https://jaxwang28.github.io) 2017 -- {Year} | [Github](https://github.com/jaxwang28)"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
  block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
  inline = [ [ "\\(", "\\)" ] ]


[services]
  #[services.disqus]
    #shortname = 'blog-jax'
  [services.googleAnalytics]
    ID = '7S26TLKGMX'

[params.busuanzi]
enable = true
